srcs_application += Tool.cpp SplineToolProperties.cpp BucketProperties.cpp \
	ToolsController.cpp RectangleProperties.cpp CircleProperties.cpp TextProperties.cpp ToolsMenu.cpp

vpath %.cpp $(APPLICATION_DIR)/Tools