VIEW_LIB_DIR := $(PROJECT_DIR)/ViewLib

srcs_view_lib := SimpleWindow.cpp

include $(VIEW_LIB_DIR)/Graphics/makefile
include $(VIEW_LIB_DIR)/Event/makefile
include $(VIEW_LIB_DIR)/ViewGroup/makefile
include $(VIEW_LIB_DIR)/View/makefile

srcs += $(srcs_view_lib)

vpath %.cpp $(VIEW_LIB_DIR)