CURRENT_DIR := $(VIEW_LIB_DIR)/Graphics

srcs_graphics := Color.cpp Canvas.cpp Text.cpp Image.cpp
objs_graphics := $(addprefix $(OBJ)/, $(srcs_graphics:.cpp=.o))

srcs += $(srcs_graphics)

vpath %.cpp $(CURRENT_DIR)