CURRENT_DIR  := $(PROJECT_DIR)/Application/ToolsProperties

srcs_application += IProperties.cpp Tool.cpp SplineToolProperties.cpp BucketProperties.cpp ToolsController.cpp RectangleProperties.cpp CircleProperties.cpp TextProperties.cpp

vpath %.cpp $(CURRENT_DIR)