CURRENT_DIR := $(VIEW_LIB_DIR)/ViewGroup

srcs_view_groups := LinearLayout.cpp ScrollLayout.cpp ViewGroup.cpp
objs_view_groups := $(addprefix $(OBJ)/, $(srcs_view_groups:.cpp=.o))

srcs += $(srcs_view_groups)

vpath %.cpp $(CURRENT_DIR)