CURRENT_DIR := $(PROJECT_DIR)/UtilLib
UTIL_LIB_DIR := $(PROJECT_DIR)/UtilLib

include $(UTIL_LIB_DIR)/Errors/makefile
include $(UTIL_LIB_DIR)/Logs/makefile
include $(UTIL_LIB_DIR)/Text/makefile

srcs_util_lib := $(srcs_errors) $(srcs_logs) $(srcs_text)
objs_util_lib := $(objs_errors) $(objs_logs) $(objs_text)